MODEL:
  MODE: 'SID'
TRAINING:
  EPOCHS_PER_SIZE: [250, 250, 250, 250]   # 每个 patch_size 训练的 epoch 数
  PATCH_SIZES: [256, 256, 384, 600]      # 训练时用的 patch 尺寸
  BATCH_SIZES: [4, 2, 2, 1]           # 每个 patch 对应的 batch 大小
  # VAL_PATCH_SIZE: 512                # 验证时 patch 大小
  TRAIN_DIR_NORMAL: "/disk527/Commondisk/a804_qkf/vscodeproject/data/SID_png/train/high"   # 训练集路径
  TRAIN_DIR_LOW: "/disk527/Commondisk/a804_qkf/vscodeproject/data/SID_png/train/low" 
  VAL_DIR_NORMAL: "/disk527/Commondisk/a804_qkf/vscodeproject/data/SID_png/eval/high"       # 验证集路径
  VAL_DIR_LOW: "/disk527/Commondisk/a804_qkf/vscodeproject/data/SID_png/eval/low"
  SAVE_DIR: "snapshots/SID"         # 模型与日志保存路径
  VAL_AFTER_EVERY: 1                  # 每多少个 epoch 验证一次

OPTIM:
  BETA1: 0.9
  BETA2: 0.999
